# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Ali Yalcin Kaya
tagline: On Digital Marketing Performance
  # These paths are to the main pages Jekyll-Bootstrap ships with.
  # Some JB helpers refer to these paths; change them here if needed.
  categories_path : /categories.html
  tags_path : /tags.html