name: Ali Yalcin Kaya
markdown: redcarpet
pygments: true
permalink: /:categories/:year/:month/:day/:title 

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Ali Yalcin Kaya
tagline: On Digital Marketing Performance